### PR TITLE
feat: add ability to define custom fields

### PR DESCRIPTION
**Pull request by FacundoSpira**
## Title
Add ability to add custom fields in edit.

## Type of Change

- [x] New feature
- [ ] Bug fix
- [ ] Documentation update
- [ ] Example update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Issue
#405 

## Description
- Changed some types to allow a new field `customFields`, and also let `aliases` and `display` allow receiving other strings apart from the model fields. It's made in such way that those fields are still suggesting the model keys in the autocomplete, but it won't error when defining any other string. 
- In server, added a `addCustomProperties` method to the `pipe` function that reads the `customFields` property and adds them to the schema.
- Added `mode` to the custom inputs prop, since it's really useful to have when the input needs to have different behaviors on create and on edit. 
- Added an example with the usecase mentioned in the issue: added `hashedPassword` field to the `User` model, and created a custom field `newPassword` with a custom input component to be able to manage changing passwords. For this I also used the new hooks feature.

## Screenshots

https://github.com/user-attachments/assets/a96ec3e6-c1ef-4109-af8b-993a0b16fc7f

### CODE REVIEW

**Review by foyarash — APPROVED** [review]
Nice stuff, thank you !

**Comment by foyarash** [comment]
> @foyarash I'm not exactly sure what's failing. Seems like a timeout, but tests run fine locally Screenshot 2024-09-09 at 7 35 43 AM

Seems its the page router test that fails

`BASE_URL=http://localhost:3000/pagerouter/admin yarn test:e2e`

**Comment by FacundoSpira** [comment]
> Seems its the page router test that fails
> 
> `BASE_URL=http://localhost:3000/pagerouter/admin yarn test:e2e`

Ohh, makes sense. I will make the prop in the database optional then. I added it as an example for the app router, but custom inputs don't work in pages, so it makes no sense for it to be mandatory

**Comment by foyarash** [comment]
> > Seems its the page router test that fails
> > `BASE_URL=http://localhost:3000/pagerouter/admin yarn test:e2e`
> 
> Ohh, makes sense. I will make the prop in the database optional then. I added it as an example for the app router, but custom inputs don't work in pages, so it makes no sense for it to be mandatory

Custom inputs should be working on page router. The page router options already includes a custom input for the `birthDate` property on a user

**Comment by FacundoSpira** [comment]
> > > Seems its the page router test that fails
> > > `BASE_URL=http://localhost:3000/pagerouter/admin yarn test:e2e`
> > 
> > 
> > Ohh, makes sense. I will make the prop in the database optional then. I added it as an example for the app router, but custom inputs don't work in pages, so it makes no sense for it to be mandatory
> 
> Custom inputs should be working on page router. The page router options already includes a custom input for the `birthDate` property on a user

Thanks! Just added the same example for the pages router

**Pull request merged**
