### PR TITLE
feat: add support for scalar array

### PR DESCRIPTION
**Pull request by foyarash**
## Title

Add support for Prisma scalar array 

## Type of Change

- [x] New feature
- [ ] Bug fix
- [ ] Documentation update
- [ ] Example update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Issue

#322 

## Description

Add support for Prisma scalar arrays. Currently supported scalar types are strings and numbers.

In the list, the array is displayed as a count. The PR also includes support search inside the array (case sensitive & exact content as its the only supported way on Prisma)

## Screenshots

image

image

### CODE REVIEW

**Comment by FacundoSpira** [comment]
Hey @foyarash, first of all thanks for the quick response to the issue and for this PR. It's looking really good. I tried some things last Friday, and did a similar approach than what you did here with the separation of different cases in the `ArrayField` component, but I had some problems with the `@rjsf` that I'm not that familiar with.

One thing that I was noticing that it can be added (maybe you prefer to do it in another PR with a separate issue) is the support for array of enums. What I saw is that we can add it as well to the `ArrayField` component by doing
```tsx
if (dmmfField?.kind === "enum" && dmmfField?.isList)
```
Then, what we really need is a select with the possible enum values. We can even get those enums from the schema by doing `schema.enum`, which returns an array of objects with a `label` and `value`. So we can even use this info to render a multi-select with a fixed number of options. What do you think?

Thanks again! :)

**Comment by foyarash** [comment]
Hello @FacundoSpira 

Interesting, i actually didnt think about the use case with enums ! This can be part of another PR when this one will be merged. This will require to use the same logic we do in [MultiSelectWidget](https://github.com/premieroctet/next-admin/blob/main/packages/next-admin/src/components/inputs/MultiSelect/MultiSelectWidget.tsx)

Let me know if you want to work on this stuff !

**Comment by FacundoSpira** [comment]
> Hello @FacundoSpira
> 
> Interesting, i actually didnt think about the use case with enums ! This can be part of another PR when this one will be merged. This will require to use the same logic we do in [MultiSelectWidget](https://github.com/premieroctet/next-admin/blob/main/packages/next-admin/src/components/inputs/MultiSelect/MultiSelectWidget.tsx)
> 
> Let me know if you want to work on this stuff !

Sure, I'll do it! I'll raise a PR pointing to this one shortly :)

**Review by cregourd — COMMENTED** [review]
Perfect, just one thing, in demo example on `Post` entity, the `tags` fields is required, but there is no error when I submit without any `tags`

**Pull request merged**
